### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gliehu** [CDTrans/CDTrans#4]
I have followed the Requirements of README.md and tried to run the code for a whole day. however, there are still several issues unresolved. I searched on the Google but it did not work. I want get some advice please.

1. pretrain
+ bash scripts/pretrain/officehome/run_officehome_Ar.sh deit_small
![1](https://user-images.githubusercontent.com/40121528/149624089-4d50c99d-93d0-4b9e-a947-6c817c1bbcb0.png)
But The Art/Pan/00002.jpg is **exist** in officehome dataset and Art.txt

2. train
+ bash scripts/uda/office31/run_office_amazon.sh deit_small
![2](https://user-images.githubusercontent.com/40121528/149624104-8ebf17ce-2394-4855-a00e-5448f4c1c94c.png)

+ bash scripts/uda/visda/run_visda.sh deit_small
![3](https://user-images.githubusercontent.com/40121528/149624128-d8d363ab-3ed1-4e55-8ee0-2c2a675bac3e.png)

**Comment by CDTrans** [comment]
Thank you for the correction. I have fixed it in the new updated version of this project. You can now re-download it or pull it with git. very thank you.

**Comment by CDTrans** [comment]
Note that the 'Real World' domain directory name of the Office-Home should be renamed to 'Real_World' for dataset loading. Otherwise, you may encounter "FileNotFoundError: [Errno 2] No such file or directory".

**Comment by CDTrans** [comment]
I haven't heard from you for a long time, I will now close this issue. If you have new questions, you can reopen the issue
