### ISSUE TITLE
Results are not consistent with the paper

### ISSUE THREAD

**Issue by SikaStar** [CDTrans/CDTrans#5]
Hi, thanks for your great work! Why are the results of DomainNet in this [README](https://github.com/CDTrans/CDTrans#table-4-uda-results-on-domainnet) not consistent with those in Table. 4 in your [paper](https://openreview.net/forum?id=XGzk5OKWFFc) ?

**Comment by CDTrans** [comment]
The result in the paper is an earlier submission version. The result of the project README is the latest version of our model.
Thanks for your mind, we will update the result of the arxiv version. Now you can get the latest version from openreview.net https://openreview.net/forum?id=XGzk5OKWFFc
