### ISSUE TITLE
Problem in DomainNet training setting

### ISSUE THREAD

**Issue by SikaStar** [CDTrans/CDTrans#6]
Hi, why do you use combine the training set and the testing set in DomainNet for training and testing? For example, when taking "clipart"  as the target domain, you use `clipart.txt` (combining `clipart_train.txt` and `clipart_test.txt`) for both training and testing, which means all the testing samples have been seen during training. For another word, why not use `clipart_train.txt` for training and use `clipart_test.txt` for testing?

**Comment by CDTrans** [comment]
We have also done experiments at the beginning, using *_train.txt samples for unlabeled data training and *_test.txt samples for testing. Later we found that the settings of the DomainNet are not consistent with the settings of other previous datasets of UDA, Office-31, Office-Home, VisDA-2017, which used the entire target sample for training and testing. 
We decided to follow the setup method of other UDA datasets and use samples from the whole target domain for training and testing.
The server resources were tight at that time and the results show that it also exceeds the methods of other comparisons in this setting. So I did not run all the *_train.txt and *_test.txt experiments.

**Comment by SikaStar** [comment]
> We have also done experiments at the beginning, using *_train.txt samples for unlabeled data training and *_test.txt samples for testing. Later we found that the settings of the DomainNet are not consistent with the settings of other previous datasets of UDA, Office-31, Office-Home, VisDA-2017, which used the entire target sample for training and testing. We decided to follow the setup method of other UDA datasets and use samples from the whole target domain for training and testing. The server resources were tight at that time and the results show that it also exceeds the methods of other comparisons in this setting. So I did not run all the *_train.txt and *_test.txt experiments.

Thanks for your replay! In order to avoid misleading the reader, please kindly to provide these details in the paper.

**Comment by CDTrans** [comment]
Thanks for your advice, we will add the details of the dataset settings.
