### ISSUE TITLE
Visualising the attention

### ISSUE THREAD

**Issue by finlay96** [CDTrans/CDTrans#7]
Just wondering if you had any code to allow for visualization of the attention maps of size (B, N, num_patches+1, num_patches+1) to create something like Figure 1a in the paper. 

Thanks!

**Comment by cwhgn** [comment]
You can save out the attention weights from any layer you want to see, and use the following codes to show the attention weights:

> plt.figure(figsize=(6,6))
> m = np.load('xxx') # saved attention weights
> sns.heatmap(m,annot=True,cmap='Reds',annot_kws={'size':18,'weight':'bold'})
> plt.show()

**Comment by EkMi00** [comment]
hi @finlay96 , can you please share if you have managed to recreate the result from the paper?
