### ISSUE TITLE
Question about the Loss term in this code

### ISSUE THREAD

**Issue by myukzzz** [CDTrans/CDTrans#9]
Hello, I think there exsists a logical error in your code.

In processor_uda.py, the loss Loss1 of the target samples is not consistant with the loss term your proposed in paper.

Here I take out the error line 339

loss1 = loss_fn(score1, feat1, t_pseudo_target, target_cam) 

and the line 337

(self_score1, self_feat1, self_prob1), (score2, feat2, prob2), (score1, feat1, prob1), cross_attn  = model(img, t_img, target, cam_label=target_cam, view_label=target_view ) # output: source , target , source_target_fusion

In your code, you use the cls Loss of the fusion samples instead of the target samples, then the loss is employed to optimize the network as the target cls Loss

This is not reasonable and not consistant with Fig. (2) in your paper.

Hope you can check the code. Thanks

**Comment by CDTrans** [comment]
Thanks for your mind. The original score item order is the source, fusion, and target. When I sorted out the code I changed the order and forgot to change the loss order. Now I update the code to fix it. Thanks again.
